### ISSUE TITLE
on_connect() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by gzin** [marceloleitner/mqtt2rrd#1]
When starting the script something went wrong:

# ./mqtt2rrd.py -v
Traceback (most recent call last):
  File "./mqtt2rrd.py", line 113, in <module>
    client.loop_forever()
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1849, in _packet_read
    rc = self._packet_handle()
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 2311, in _packet_handle
    return self._handle_connack()
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 2372, in _handle_connack
    self.on_connect(self, self._userdata, flags_dict, result)
TypeError: on_connect() takes 3 positional arguments but 4 were given

I'm using Ubuntu 18.04.
What's wrong?

Best regards,
Guenther

**Comment by marceloleitner** [comment]
Hi Guenther. That's an issue within paho-mqtt. Which version are you using?
I just tested with 1.5.0 and it worked.
I installed it with pip3 install --user paho-mqtt on a Fedora 31.

**Comment by marceloleitner** [comment]
Ahh. You're probably using MQTTv5, then it needs the 4th parameter. Please try this patch:

```
--- a/mqtt2rrd.py
+++ b/mqtt2rrd.py
@@ -8,7 +8,7 @@ import logging
 import argparse

 # The callback for when the client receives a CONNACK response from the server.
-def on_connect(client, userdata, rc):
+def on_connect(client, userdata, rc, properties=None):
     log.info("Connected with result code "+str(rc))

     # Subscribing in on_connect() means that if we lose the connection and
```

**Comment by SudilHasitha** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3030, in _handle_connack
    self, self._userdata, flags_dict, result)
TypeError: on_connect() missing 1 required positional argument: 'rc'
